### ISSUE TITLE
issue / suggestion

### ISSUE THREAD

**Issue by twituserjosh** [PrinceS25/StockAlertBot#19] opened 2021-01-11 22:50 UTC
![image](https://user-images.githubusercontent.com/40156954/104247170-3a1e5b80-5435-11eb-9d70-50d303ed60d9.png)

microcenter seems to spam a bit (not sure if an issue with other stores as it did detect a PS5 from target and only pinged once, but anyway to add an "if instock send hook, then if it goes out of stock after it pings "sold out?"

**Comment by PrinceS25** [comment] 2021-01-12 00:43
Unfortunately, the "spam" is currently by design. I currently have it notify Discord and open the URL every 5 minutes and if you look at the time of the messages, that's exactly what's happening. However, this design is temporary and I plan on changing it. May I ask you, do you prefer that it only sent the notification message once to discord while it's in stock?

Also, was the Ryzen 5900x actually in stock at Microcenter? :O

**Comment by twituserjosh** [comment] 2021-01-12 05:14
it was in stock! and yes just one (i use slack)

**Comment by PrinceS25** [comment] 2021-01-12 23:19
Microcenter's website is not immediately updated. I once received an alert when they had 4+ in stock. As I got on the freeway, it dropped to 1 and they told me over the phone they're out of stock. I stopped tracking Microcenter because of this reason. You'd have to live next door if you plan on getting something in demand.

I'll let you know once I implement better timers. I will close this issue for now.

**Closed by PrinceS25** 2021-01-12 23:19 UTC
